apiVersion: batch/v1
kind: Job
metadata:
  name: math-job
spec:
  completions: 3
  template:
    spec:
      containers:
        - image: ubuntu
          name: math-add
          command: ["expr","3","+","4"]
      restartPolicy: Never
