apiVersion: v1
kind: LimitRange
metadata:
  name: limit-1
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 1Gi
      defaultRequest:
        cpu: 50m
        memory: 1Gi
      max:
        cpu: "1"
        memory: 1Gi
      min:
        cpu: 10m
        memory: 100Mi
      
           
